const information = [
  {
    id: "1",
    img: "http://localhost:5173/Project/alpha.png",
    name: "Alpha beauty",
    overView: "This is a instagram clone ",
    tools: ["javascript ", "react", "Telwind", "Framer Motion", "gsap"],
  },
  {
    id: "2",
    img: "http://localhost:5173/Project/apple.png",
    name: "iPhone 15",
    overView: "This is a Mannsales ",
    tools: ["java", "react", "css", "html"],
  },
  {
    id: "3",
    img: "http://localhost:5173/Project/office.png",
    name: "Office",
    overView: "This is a instagram clone ",
    tools: ["javascript ", "react", "Telwind", "Framer Motion", "gsap"],
  },
  {
    id: "4",
    img: "http://localhost:5173/Project/boble.png",
    name: "Boble Game",
    overView: "This is a Mannsales ",
    tools: ["java", "react", "css", "html"],
  },
  {
    id: "5",
    img: "http://localhost:5173/Project/ola.png",
    name: "Ola",
    overView: "This is a instagram clone ",
    tools: ["javascript ", "react", "Telwind", "Framer Motion", "gsap"],
  },
  {
    id: "6",
    img: "http://localhost:5173/Project/food.png",
    name: "Food app",
    overView: "This is a instagram clone",
    tools: ["java", "react", "css", "html"],
  },
  {
    id: "7",
    img: "http://localhost:5173/Project/liber.png",
    name: "Liber",
    overView: "This is a instagram clone",
    tools: ["java", "react", "css", "html"],
  },
  {
    id: "8",
    img: "http://localhost:5173/Project/pass.png",
    name: "Rock,paper,scissors Game",
    overView: "This is a instagram clone",
    tools: ["java", "react", "css", "html"],
  },
  {
    id: "9",
    img: "http://localhost:5173/Project/ox.png",
    name: "ox game ",
    overView: "This is a instagram clone",
    tools: ["java", "react", "css", "html"],
  },
  {
    id: "10",
    img: "http://localhost:5173/Project/timer.png",
    name: "Timer",
    overView: "This is a instagram clone",
    tools: ["java", "react", "css", "html"],
  },
  {
    id: "11",
    img: "http://localhost:5173/Project/work.png",
    name: "Worl Studio",
    overView: "This is a instagram clone",
    tools: ["java", "react", "css", "html"],
  },
  {
    id: "11",
    img: "http://localhost:5173/Project/sp.png",
    name: "Marvel",
    overView: "This is a instagram clone",
    tools: ["java", "react", "css", "html"],
  },
  {
    id: "12",
    img: "http://localhost:5173/Project/sportify.png",
    name: "sportify",
    overView: "This is a instagram clone",
    tools: ["java", "react", "css", "html"],
  },
  {
    id: "13",
    img: "http://localhost:5173/Project/cyn.png",
    name: "cynthia ugwu",
    overView: "This is a instagram clone",
    tools: ["java", "react", "css", "html"],
  },
  {
    id: "14",
    img: "http://localhost:5173/Project/trevel.png",
    name: "trevel Website",
    overView: "This is a instagram clone",
    tools: ["java", "react", "css", "html"],
  },
  {
    id: "15",
    img: "http://localhost:5173/Project/colorPicker.png",
    name: "Color Picker",
    overView: "This is a instagram clone",
    tools: ["java", "react", "css", "html"],
  },
];

export default information;
